export const PERMISSIONS = {
  FULL_ACCESS: 'FULL_ACCESS',

  VIEW_USER: 'VIEW_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  VIEW_ROLE: 'VIEW_ROLE',
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',

  VIEW_PERMISSION: 'VIEW_PERMISSION',

  VIEW_CATEGORY: 'VIEW_CATEGORY',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  VIEW_BLOG: 'VIEW_BLOG',
  CREATE_BLOG: 'CREATE_BLOG',
  UPDATE_BLOG: 'UPDATE_BLOG',
  DELETE_BLOG: 'DELETE_BLOG',

  VIEW_PRODUCT: 'VIEW_PRODUCT',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',

  VIEW_ATTRIBUTE: 'VIEW_ATTRIBUTE',
  CREATE_ATTRIBUTE: 'CREATE_ATTRIBUTE',
  UPDATE_ATTRIBUTE: 'UPDATE_ATTRIBUTE',
  DELETE_ATTRIBUTE: 'DELETE_ATTRIBUTE',

  VIEW_VARIANT: 'VIEW_VARIANT',
  CREATE_VARIANT: 'CREATE_VARIANT',
  UPDATE_VARIANT: 'UPDATE_VARIANT',
  DELETE_VARIANT: 'DELETE_VARIANT',

  VIEW_ORDER: 'VIEW_ORDER',
  TRACKING_ORDER: 'TRACKING_ORDER',
  CREATE_ORDER: 'CREATE_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',

  VIEW_FILE: 'VIEW_FILE',
  CREATE_FILE: 'CREATE_FILE',
  UPDATE_FILE: 'UPDATE_FILE',
  DELETE_FILE: 'DELETE_FILE',

  VIEW_APPOINTMENT: 'VIEW_APPOINTMENT',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
  DELETE_APPOINTMENT: 'DELETE_APPOINTMENT',
};

export const ALL_USER_PERMISSIONS = [
  PERMISSIONS.VIEW_BLOG,
  PERMISSIONS.VIEW_CATEGORY,
  PERMISSIONS.VIEW_ORDER,
  PERMISSIONS.VIEW_PRODUCT,
];
