export const CategoryContent = `
    <div>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;"><em style="box-sizing:border-box;"><i>Photocopy khổ lớn hay Photocopy A0, Photocopy A1, Photocopy A2 là sao chép hình ảnh trên khổ giấy lớn. Vậy giá photo là bao nhiêu và photocopy ở đâu uy tín, nhanh chóng. Mọi thắc mắc của bạn sẽ được giải đáp trong bài viết dưới đây!</i></em></p>
        <h2 class="wp-block-heading" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.6em;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-rendering:optimizespeed;text-transform:none;white-space:normal;widows:2;width:870px;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Dịch vụ photocopy khổ lớn</strong></h2>
        <h3 class="wp-block-heading" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;margin-bottom:0.5em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-rendering:optimizespeed;text-transform:none;white-space:normal;widows:2;width:870px;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Photocopy khổ lớn</strong></h3>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Trên thực tế, có khá nhiều loại tài liệu để trình bày nội dung văn bản và hình ảnh trên các khổ giấy lớn và photocopy khổ lớn ra đời để phục vụ cho nhu cầu đó của khách hàng.</p>
        <p style="text-align:center;"><img class="wp-image-17479 entered litespeed-loaded" style="border-style:none;box-sizing:border-box;display:inline-block;height:auto;max-width:100%;opacity:1;transition:opacity 1s ease 0s;vertical-align:bottom;" src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01.jpg.webp" alt="Photocopy khổ A1" srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01.jpg.webp 900w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01-768x512.jpg.webp 768w" sizes="(max-width: 900px) 100vw, 900px" width="900" height="600" data-lazyloaded="1" data-placeholder-resp="900x600" decoding="async" data-src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01.jpg.webp" title="Photocopy khổ lớn 1" data-srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01.jpg.webp 900w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-01-768x512.jpg.webp 768w" data-sizes="(max-width: 900px) 100vw, 900px" data-ll-status="loaded"></p>
        <div class="wp-block-image size-full wp-image-15726" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <figure class="aligncenter" style="box-sizing:border-box;clear:both;display:table;margin:0px auto;">
                <figcaption style="box-sizing:border-box;caption-side:bottom;display:table-caption;margin-bottom:1em;margin-top:0.5em;"><em style="box-sizing:border-box;"><i><kbd style="box-sizing:border-box;">Photocopy khổ A1</kbd></i></em></figcaption>
            </figure>
        </div>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Photocopy khổ lớn là quá trình sao chép hình ảnh, chữ viết, thông tin trên thành nhiều bản trên các khổ giấy với&nbsp;kích cỡ khác nhau. Khổ lớn bao gồm các kích cỡ giấy bao gồm từ khổ A0, A1, A2, A3 và các khổ lớn hơn A0.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;"><a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" target="_blank" rel="noopener noreferrer" href="https://inthienhang.com/photocopy-kho-lon/">Dịch vụ photocopy khổ lớn</a> được sử dụng cho các thiết kế, bản vẽ và các loại tài liệu, đáp ứng được mọi nhu cầu in và photocopy, bản vẽ khổ lớn: bản vẽ xây dựng, bản vẽ kỹ thuật, bản vẽ hoàn công…</p>
        <p style="text-align:center;"><img class="wp-image-17392 entered litespeed-loaded" style="border-style:none;box-sizing:border-box;display:inline-block;height:auto;max-width:100%;opacity:1;transition:opacity 1s ease 0s;vertical-align:bottom;" src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad.jpg.webp" alt="In bản vẽ thiết kế khổ lớn" srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad.jpg.webp 800w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad-560x400.jpg.webp 560w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad-768x548.jpg.webp 768w" sizes="(max-width: 800px) 100vw, 800px" width="800" height="571" data-lazyloaded="1" data-placeholder-resp="800x571" decoding="async" data-src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad.jpg.webp" title="Photocopy khổ lớn 2" data-srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad.jpg.webp 800w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad-560x400.jpg.webp 560w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-autocad-768x548.jpg.webp 768w" data-sizes="(max-width: 800px) 100vw, 800px" data-ll-status="loaded"></p>
        <div class="wp-block-image size-medium wp-image-15727" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <figure class="aligncenter size-full" style="box-sizing:border-box;clear:both;display:table;margin:0px auto;">
                <figcaption style="box-sizing:border-box;caption-side:bottom;display:table-caption;margin-bottom:1em;margin-top:0.5em;"><em style="box-sizing:border-box;"><i><kbd style="box-sizing:border-box;">Photocopy khổ lớn bản vẽ kỹ thuật</kbd></i></em></figcaption>
            </figure>
        </div>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Một số bài báo cáo, tài liệu được sử dụng với mục đích cho nhiều người xem hoặc mục đích giải thích giới thiệu tới mọi người thường được photo khổ lớn để tiện cho quá trình theo dõi của mọi người trong quá trình thảo luận.</p>
        <h3 class="wp-block-heading" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;margin-bottom:0.5em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-rendering:optimizespeed;text-transform:none;white-space:normal;widows:2;width:870px;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Kích thước giấy photo&nbsp;</strong></h3>
        <p style="text-align:center;"><img class="wp-image-15593 entered litespeed-loaded" style="border-style:none;box-sizing:border-box;display:inline-block;height:auto;max-width:100%;opacity:1;transition:opacity 1s ease 0s;vertical-align:bottom;" src="https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6-600x400.jpg.webp" alt="Kích thước giấy photocopy" srcset="https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6-768x512.jpg.webp 768w, https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6.jpg.webp 900w" sizes="(max-width: 600px) 100vw, 600px" width="600" height="400" data-lazyloaded="1" data-placeholder-resp="600x400" decoding="async" data-src="https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6-600x400.jpg.webp" title="Photocopy khổ lớn 3" data-srcset="https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6-768x512.jpg.webp 768w, https://inthienhang.com/wp-content/uploads/2020/05/Kich-Thuoc-Chuan-Kho-Giay-A0-A1-A2-A3-A4-A5-A6.jpg.webp 900w" data-sizes="(max-width: 600px) 100vw, 600px" data-ll-status="loaded"></p>
        <div class="wp-block-image size-medium wp-image-15593" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <figure class="aligncenter" style="box-sizing:border-box;clear:both;display:table;margin:0px auto;">
                <figcaption style="box-sizing:border-box;caption-side:bottom;display:table-caption;margin-bottom:1em;margin-top:0.5em;"><em style="box-sizing:border-box;"><i><kbd style="box-sizing:border-box;">Kích thước giấy photocopy</kbd></i></em></figcaption>
            </figure>
        </div>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Photocopy khổ lớn bao gồm các khổ A0, A1,A2, A3 với kích thước như sau:</p>
        <ol style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;list-style:decimal;margin-bottom:1.3em;margin-top:0px;orphans:2;padding:0px;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <li style="box-sizing:border-box;margin-bottom:0.6em;">Khổ A0: 1189 x 841 mm.</li>
            <li style="box-sizing:border-box;margin-bottom:0.6em;">Khổ A1: 841 x 594 mm.</li>
            <li style="box-sizing:border-box;margin-bottom:0.6em;">Khổ A2: 594 x 420 mm.</li>
            <li style="box-sizing:border-box;margin-bottom:0.6em;">Khổ A3: 420 x 297 mm.</li>
        </ol>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Đây là kích thước tiêu chuẩn của các khổ giấy sử dụng thông thường, các khổ tiêu chuẩn khác có thể là các khổ như B0, B1, B2… ( tham khảo các khổ giấy khác: <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" target="_blank" rel="noopener">https://vi.wikipedia.org/wiki/Kh%E1%BB%95_gi%E1%BA%A5y</a>)</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Ngoài ra, đối với các khổ không theo tiêu chuẩn nào thì được gọi tên theo kích thước hai cạnh của mặt giấy. Việc lựa chọn kích thước in khổ lớn tùy thuộc vào nhu cầu của bạn. Bạn có thể lựa chọn khổ giấy photo theo chiều dài và chiều rộng của khổ giấy.</p>
        <h3 class="wp-block-heading" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;margin-bottom:0.5em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-rendering:optimizespeed;text-transform:none;white-space:normal;widows:2;width:870px;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Dịch vụ photo Hà Nội</strong></h3>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Để có một bản photocopy khổ lớn đẹp, hình ảnh và màu sắc rõ nét, không nhòe mực, không bay màu thì bạn nên lựa chọn một dịch vụ in uy tín, bảo đảm chất lượng sản phẩm in cho bạn về mặt thời gian.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Tuy nhiên, có nhiều cửa hàng khi in các sản phẩm photocopy khổ lớn chất lượng không tốt mà giá thành lại đắt. Đặc biệt, với những thành phố lớn như Hà Nội. Vậy để có được những bản photo khổ lớn tốt nhất cho bạn, nên sử dụng dịch vụ photocopy khổ lớn ở đâu?</p>
        <p style="text-align:center;"><img class="wp-image-15624 entered litespeed-loaded" style="border-style:none;box-sizing:border-box;display:inline-block;height:auto;max-width:100%;opacity:1;transition:opacity 1s ease 0s;vertical-align:bottom;" src="https://inthienhang.com/wp-content/uploads/2020/05/dich-vu-in-thien-hang-2.jpg.webp" alt="Dịch vụ In Thiên Hằng" width="594" height="317" data-lazyloaded="1" data-placeholder-resp="594x317" decoding="async" data-src="https://inthienhang.com/wp-content/uploads/2020/05/dich-vu-in-thien-hang-2.jpg.webp" title="Photocopy khổ lớn 4" data-ll-status="loaded"></p>
        <div class="wp-block-image size-full wp-image-15624" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <figure class="aligncenter" style="box-sizing:border-box;clear:both;display:table;margin:0px auto;">
                <figcaption style="box-sizing:border-box;caption-side:bottom;display:table-caption;margin-bottom:1em;margin-top:0.5em;"><em style="box-sizing:border-box;"><i><kbd style="box-sizing:border-box;">Dịch vụ In Thiên Hằng</kbd></i></em></figcaption>
            </figure>
        </div>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Công ty TNHH Dịch vụ Thiên Hằng là đơn vị chuyên cung cấp các dịch vụ in – photocopy, tất tần tật những dịch vụ có liên quan đến in ấn và photocopy đều được cung cấp và phục vụ tận tình. Photocopy khổ lớn cũng là một dịch vụ nhỏ nằm trong danh sách dịch vụ được cung cấp bởi In Thiên Hằng.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Tại In Thiên Hằng, các dịch vụ photocopy A0, in – photocopy A1, và in – photocopy A2, photocopy A3 đều được thực hiện photo trên máy photocopy ricoh kỹ thuật số tốc độ cao và máy ocer. Các máy này có đặc điểm là cho phép photocopy một chiều đến 90cm và chiều dài thì đến khoảng 1.200cm.</p>
        <p style="text-align:center;"><img class="wp-image-17480 entered litespeed-loaded" style="border-style:none;box-sizing:border-box;display:inline-block;height:auto;max-width:100%;opacity:1;transition:opacity 1s ease 0s;vertical-align:bottom;" src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02.jpg.webp" alt="Photocopy bản vẽ kỹ thuật khổ lớn" srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02.jpg.webp 900w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02-768x512.jpg.webp 768w" sizes="(max-width: 900px) 100vw, 900px" width="900" height="600" data-lazyloaded="1" data-placeholder-resp="900x600" decoding="async" data-src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02.jpg.webp" title="Photocopy khổ lớn 5" data-srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02.jpg.webp 900w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-02-768x512.jpg.webp 768w" data-sizes="(max-width: 900px) 100vw, 900px" data-ll-status="loaded"></p>
        <div class="wp-block-image size-medium wp-image-15728" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <figure class="aligncenter size-full" style="box-sizing:border-box;clear:both;display:table;margin:0px auto;">
                <figcaption style="box-sizing:border-box;caption-side:bottom;display:table-caption;margin-bottom:1em;margin-top:0.5em;"><em style="box-sizing:border-box;"><i><kbd style="box-sizing:border-box;">Photocopy khổ lớn</kbd></i></em></figcaption>
            </figure>
        </div>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Với kích thước tối đa đó của máy in thì ngoài kích thước khổ A0 khách hàng có thể lựa chọn in các tài liệu lớn hơn khổ A0 và lựa chọn một kích thước photocopy khổ lớn bất kỳ. Vì thế in – photocopy A0 sẽ trở nên đơn giản, dễ dàng hơn rất nhiều.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Hơn nữa, việc sử dụng máy photocopy khổ lớn kỹ thuật số làm cho các sản phẩm photocopy khổ lớn được in ra với độ ổn định cao, chất lượng cực đẹp và không bao giờ bay hay mờ mực.</p>
        <p style="text-align:center;"><img class="wp-image-17484 entered litespeed-loaded" style="border-style:none;box-sizing:border-box;display:inline-block;height:auto;max-width:100%;opacity:1;transition:opacity 1s ease 0s;vertical-align:bottom;" src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04.jpg.webp" alt="Hoàn thiện sản phẩm in/photo bản vẽ thiết kế khổ lớn" srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04.jpg.webp 900w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04-768x512.jpg.webp 768w" sizes="(max-width: 900px) 100vw, 900px" width="900" height="600" data-lazyloaded="1" data-placeholder-resp="900x600" decoding="async" data-src="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04.jpg.webp" title="Photocopy khổ lớn 6" data-srcset="https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04.jpg.webp 900w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04-600x400.jpg.webp 600w, https://inthienhang.com/wp-content/uploads/in-ban-ve-thiet-ke-04-768x512.jpg.webp 768w" data-sizes="(max-width: 900px) 100vw, 900px" data-ll-status="loaded"></p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Khách hàng có thể hoàn toàn yên tâm khi sử dụng dịch vụ photocopy khổ lớn tại In Thiên Hằng, công ty với những nhân viên lành nghề, dày dặn kinh nghiệm, đảm bảo thời gian hoàn thiện sản phẩm và chất lượng của sản phẩm photo. Các đơn hàng sẽ được hoàn thành trong thời gian sớm nhất mà sản phẩm của bạn vẫn đẹp và sắc nét trong từng chi tiết nhỏ nhất.</p>
        <figure class="wp-block-embed is-type-rich is-provider-trinh-xử-ly-nhung wp-block-embed-trinh-xử-ly-nhung wp-embed-aspect-16-9 wp-has-aspect-ratio" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);display:block;font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin:0px 0px 1.3em;orphans:2;overflow-wrap:break-word;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <div class="wp-block-embed__wrapper" style="box-sizing:border-box;position:relative;text-align:center;"><iframe class="entered litespeed-loaded" style="box-sizing:border-box;max-width:100%;" data-lazyloaded="1" src="https://www.youtube.com/embed/LboXrO8RiOc?feature=oembed" title="In - Photocopy khổ lớn: A0, A1, A2 giá rẻ | IN THIÊN HẰNG" width="1020" height="574" data-src="https://www.youtube.com/embed/LboXrO8RiOc?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" data-ll-status="loaded"></iframe></div>
        </figure>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Ngoài dịch vụ photocopy A0, A1, A2, A3 nói riêng thì các dịch vụ khác tại In Thiên Hằng được chúng tôi cung cấp ra thị trường với giá rẻ nhất, thời gian nhanh nhất và chất lượng đẹp nhất tại Hà Nội.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Xem thêm: <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" target="_blank" rel="noopener noreferrer" href="https://inthienhang.com/in-mau-a4/">in màu</a>, <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" target="_blank" rel="noopener noreferrer" href="https://inthienhang.com/in-decal/">in decal</a>, <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" target="_blank" rel="noopener noreferrer" href="https://inthienhang.com/in-den-trang/">in đen trắng.</a></p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">In Thiên Hằng còn cung cấp dịch vụ giao hàng tận nơi cho khách hàng và thời gian giao hàng thì tùy thuộc vào yêu cầu của khách hàng. Các sản phẩm được giao ưu tiên cho quý khách nào thực sự cần gấp, lấy ngay, giao hàng đúng hẹn không sai một phút, cam bằng văn bản luôn, bao thầu về giá luôn.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Nếu bạn vẫn còn đang phân vân không biết nên lựa chọn cơ sở photocopy nào thì In Thiên Hằng là sự lựa chọn hoàn hảo cho bạn.</p>
        <h2 class="wp-block-heading" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.6em;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-rendering:optimizespeed;text-transform:none;white-space:normal;widows:2;width:870px;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Báo giá photocopy khổ lớn</strong></h2>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Một trong những yếu tố quan trọng hàng đầu thu hút khách hàng là giá cả của sản phẩm, dịch vụ. Vậy nên những câu hỏi như: Giá photocopy khổ lớn là bao nhiêu? Photo A0 bao nhiêu tiền? Giá khi photo A1, A2 như thế nào?</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Vậy để giải đáp những thắc mắc về giá của khách hàng, In Thiên Hằng&nbsp; luôn lựa chọn công khai bảng giá photo của dịch vụ photocopy khổ lớn nói riêng và các dịch vụ in – photocopy nói chung.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Dưới đây là bảng giá photocopy A0, A1, A2 của In Thiên Hằng:</p>
        <p style="text-align:center;"><img class="wp-image-17334 entered litespeed-loaded" style="border-style:none;box-sizing:border-box;display:inline-block;height:auto;max-width:100%;opacity:1;transition:opacity 1s ease 0s;vertical-align:bottom;" src="https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon.png.webp" alt="Bảng giá in màu - photocopy khổ lớn: A0, A1, A2" srcset="https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon.png.webp 870w, https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon-800x233.png.webp 800w, https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon-768x223.png.webp 768w" sizes="(max-width: 870px) 100vw, 870px" width="870" height="253" data-lazyloaded="1" data-placeholder-resp="870x253" decoding="async" data-src="https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon.png.webp" title="Photocopy khổ lớn 7" data-srcset="https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon.png.webp 870w, https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon-800x233.png.webp 800w, https://inthienhang.com/wp-content/uploads/bang-gia-in-kho-lon-768x223.png.webp 768w" data-sizes="(max-width: 870px) 100vw, 870px" data-ll-status="loaded"></p>
        <div class="wp-block-image wp-image-11120 is-style-default" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">
            <figure class="aligncenter size-full" style="box-sizing:border-box;clear:both;display:table;margin:0px auto;">
                <figcaption style="box-sizing:border-box;caption-side:bottom;display:table-caption;margin-bottom:1em;margin-top:0.5em;"><em style="box-sizing:border-box;"><i><kbd style="box-sizing:border-box;">Bảng báo giá photocopy khổ lớn A0, A1, A2</kbd> (update: 2022)</i></em></figcaption>
            </figure>
        </div>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Chi phí bản in thấp cùng với tối ưu chi phí doanh nghiệp giúp công ty có thể cung cấp dịch vụ photocopy khổ lớn, khổ A0, A1, A2 cho quý khách với giá thành rất rẻ, chỉ có 2000đ/trang in photocopy A2 thôi, và 8000đ đối với in photocopy A0. Đối với các khổ khác ngoài khổ giấy cơ bản thì mức giá sẽ được tính tùy vào độ lớn của mặt giấy khi photo.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Số lượng photocopy giá trị càng lớn thì giá tiền sẽ càng nhỏ. Nếu muốn biết chi tiết giá tiền cho từng sản phẩm photo bạn có thể liên hệ hotine: <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" href="tel:0975500211">0975 500 211</a> – <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" href="tel:02466635 333">0866 012 015</a> để được báo giá chi tiết.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">In Thiên Hằng cam kết rằng dịch vụ photocopy A0, A1, A2 nói riêng và các dịch vụ khác được cung cấp ra thị trường với giá rẻ nhất, thời gian nhanh nhất và chất lượng đẹp nhất.</p>
        <p style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;">Trên đây là thông tin về dịch vụ photocopy khổ lớn của In Thiên Hằng. Cảm ơn các bạn đã theo dõi!</p>
        <p class="has-text-align-center" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:center;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Công ty TNHH Dịch vụ Công nghệ Thiên Hằng</strong></p>
        <p class="has-text-align-center" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:center;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Địa chỉ:</strong> 85 Trần Đại Nghĩa – phường Bách Khoa – quận Hai Bà Trưng – Hà Nội</p>
        <p class="has-text-align-center" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:center;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Hotline: </strong><a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" href="tel:0975500211">0975 500 211</a> – <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" href="tel:02466635 333">0866 012 015</a></p>
        <p class="has-text-align-center" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;margin-bottom:1.3em;margin-top:0px;orphans:2;text-align:center;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;"><strong style="box-sizing:border-box;font-weight:bolder;">Email:</strong> <a style="background-color:transparent;box-sizing:border-box;color:rgb(9, 112, 209);text-decoration:none;touch-action:manipulation;" href="mailto:inthienhang@gmail.com">inthienhang@gmail.com</a></p>
        <h2 class="wp-block-heading" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.6em;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;letter-spacing:normal;line-height:1.3;margin-bottom:0.5em;margin-top:0px;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-rendering:optimizespeed;text-transform:none;white-space:normal;widows:2;width:870px;word-spacing:0px;"><strong>Câu hỏi thường gặp</strong></h2>
        <div class="rank-math-block" style="-webkit-text-stroke-width:0px;background-color:rgb(255, 255, 255);box-sizing:border-box;color:rgb(0, 0, 0);font-family:Roboto, sans-serif;font-size:16px;font-style:normal;font-variant-caps:normal;font-variant-ligatures:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:start;text-decoration-color:initial;text-decoration-style:initial;text-decoration-thickness:initial;text-indent:0px;text-transform:none;white-space:normal;widows:2;word-spacing:0px;" id="rank-math-faq">
            <div class="rank-math-list " style="box-sizing:border-box;">
                <div class="rank-math-list-item" style="box-sizing:border-box;" id="faq-question-1624244169547">
                    <h3 class="rank-math-question " style="box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;margin-bottom:0.5em;margin-top:0px;text-rendering:optimizespeed;width:870px;"><strong>Photocopy khổ lớn được áp dụng cho những khổ giấy nào?</strong></h3>
                    <div class="rank-math-answer " style="box-sizing:border-box;">
                        <p style="box-sizing:border-box;margin-bottom:1.3em;margin-top:0px;">Các khổ giấy cỡ lớn hiện nay bao gồm: khổ A0, A1, A2 và các khổ lớn hơn khổ A0</p>
                    </div>
                </div>
                <div class="rank-math-list-item" style="box-sizing:border-box;" id="faq-question-1624244354970">
                    <h3 class="rank-math-question " style="box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;margin-bottom:0.5em;margin-top:0px;text-rendering:optimizespeed;width:870px;"><strong>Photocopy khổ lớn được hiểu như nào?</strong></h3>
                    <div class="rank-math-answer " style="box-sizing:border-box;">
                        <p style="box-sizing:border-box;margin-bottom:1.3em;margin-top:0px;">Photocopy khổ lớn là quá trình sao chép hình ảnh, chữ viết, thông tin trên thành nhiều bản trên các khổ giấy với&nbsp;kích cỡ khác nhau. Khổ lớn bao gồm các kích cỡ giấy bao gồm từ khổ A0, A1, A2, A3 và các khổ lớn hơn A0.</p>
                    </div>
                </div>
                <div class="rank-math-list-item" style="box-sizing:border-box;" id="faq-question-1624244375874">
                    <h3 class="rank-math-question " style="box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;margin-bottom:0.5em;margin-top:0px;text-rendering:optimizespeed;width:870px;"><strong>Photo khổ lớn được ứng dụng như nào?</strong></h3>
                    <div class="rank-math-answer " style="box-sizing:border-box;">
                        <p style="box-sizing:border-box;margin-bottom:1.3em;margin-top:0px;">Dịch vụ photocopy khổ lớn được sử dụng cho các thiết kế, bản vẽ và các loại tài liệu, đáp ứng được mọi nhu cầu in và photocopy, bản vẽ khổ lớn: bản vẽ xây dựng, bản vẽ kỹ thuật, bản vẽ hoàn công…</p>
                    </div>
                </div>
                <div class="rank-math-list-item" style="box-sizing:border-box;" id="faq-question-1624244408474">
                    <h3 class="rank-math-question " style="box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;margin-bottom:0.5em;margin-top:0px;text-rendering:optimizespeed;width:870px;"><strong>Kích thước các khổ giấy cỡ lớn phổ biến?</strong></h3>
                    <div class="rank-math-answer " style="box-sizing:border-box;">
                        <p style="box-sizing:border-box;margin-bottom:1.3em;margin-top:0px;">Khổ A0: 1189 x 841 mm. Khổ A1: 841 x 594 mm. Khổ A2: 594 x 420 mm.</p>
                    </div>
                </div>
                <div class="rank-math-list-item" style="box-sizing:border-box;" id="faq-question-1624244457077">
                    <h3 class="rank-math-question " style="box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;margin-bottom:0.5em;margin-top:0px;text-rendering:optimizespeed;width:870px;"><strong>Tại In Thiên Hằng dịch vụ có gì nổi bật?</strong></h3>
                    <div class="rank-math-answer " style="box-sizing:border-box;">
                        <p style="box-sizing:border-box;margin-bottom:1.3em;margin-top:0px;">Tại In Thiên Hằng, các dịch vụ photocopy A0, in – photocopy A1, và in – photocopy A2, photocopy A3 đều được thực hiện photo trên máy photocopy ricoh kỹ thuật số tốc độ cao và máy ocer. Các máy này có đặc điểm là cho phép photocopy một chiều đến 90cm và chiều dài thì đến khoảng 1.200cm.</p>
                    </div>
                </div>
                <div class="rank-math-list-item" style="box-sizing:border-box;" id="faq-question-1624244546902">
                    <h3 class="rank-math-question " style="box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;margin-bottom:0.5em;margin-top:0px;text-rendering:optimizespeed;width:870px;"><strong>In Thiên Hằng có hỗ trợ giao hàng không?</strong></h3>
                    <div class="rank-math-answer " style="box-sizing:border-box;">
                        <p style="box-sizing:border-box;margin-bottom:1.3em;margin-top:0px;">In Thiên Hằng có cung cấp dịch vụ giao hàng tận nơi cho khách hàng và thời gian giao hàng thì tùy thuộc vào yêu cầu của khách hàng. Các sản phẩm được giao ưu tiên cho quý khách nào thực sự cần gấp, lấy ngay, giao hàng đúng hẹn không sai một phút, cam bằng văn bản luôn, bao thầu về giá luôn.</p>
                    </div>
                </div>
                <div class="rank-math-list-item" style="box-sizing:border-box;" id="faq-question-1624244606783">
                    <h3 class="rank-math-question " style="box-sizing:border-box;color:rgb(221, 51, 51);font-family:Roboto, sans-serif;font-size:1.25em;margin-bottom:0.5em;margin-top:0px;text-rendering:optimizespeed;width:870px;"><strong>Chi phí in/photocopy khổ lớn như nào?</strong></h3>
                    <div class="rank-math-answer " style="box-sizing:border-box;">
                        <p style="box-sizing:border-box;margin-bottom:1.3em;margin-top:0px;">Chi phí bản in thấp cùng với tối ưu chi phí doanh nghiệp giúp công ty có thể cung cấp dịch vụ photocopy khổ lớn, khổ A0, A1, A2 cho quý khách với giá thành rất rẻ, chỉ có 2000đ/trang in photocopy A2 thôi, và 8000đ đối với in photocopy A0. Đối với các khổ khác ngoài khổ giấy cơ bản thì mức giá sẽ được tính tùy vào độ lớn của mặt giấy khi photo.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
`;